services:
  - type: web
    name: telegram-fix-userbot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /ping
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: TELEGRAM_SESSION
        sync: false
      - key: SOURCE_CHAT
        sync: false
      - key: TARGET_BOT_USERNAME
        value: toolsfixredupgradeGAARZ_BOT
      - key: TARGET_COMMAND
        value: /fix
      - key: STATE_FILE
        value: ./state.json
